// Auto-generated by scripts/generate-icons.js
// Do not edit manually - run `bun run icons:generate` instead

import type { FC, SVGProps } from "react";

import { ArrowUpRight } from "./generated/arrowUpRight";
import { AtSymbol } from "./generated/atSymbol";
import { Ball } from "./generated/ball";
import { Calendar } from "./generated/calendar";
import { Check } from "./generated/check";
import { Checkbox } from "./generated/checkbox";
import { ChevronDown } from "./generated/chevronDown";
import { ChevronLeft } from "./generated/chevronLeft";
import { ChevronRight } from "./generated/chevronRight";
import { ChevronsLeftRight } from "./generated/chevronsLeftRight";
import { ChevronUp } from "./generated/chevronUp";
import { Clipboard } from "./generated/clipboard";
import { Close } from "./generated/close";
import { Computer } from "./generated/computer";
import { Copy } from "./generated/copy";
import { Danger } from "./generated/danger";
import { Dark } from "./generated/dark";
import { Document } from "./generated/document";
import { Enter } from "./generated/enter";
import { Eye } from "./generated/eye";
import { EyeDropper } from "./generated/eyeDropper";
import { EyeOff } from "./generated/eyeOff";
import { Flag } from "./generated/flag";
import { Food } from "./generated/food";
import { Gift } from "./generated/gift";
import { Help } from "./generated/help";
import { Info } from "./generated/info";
import { Light } from "./generated/light";
import { LinearGauge } from "./generated/linearGauge";
import { Link } from "./generated/link";
import { Maximize } from "./generated/maximize";
import { Minimize } from "./generated/minimize";
import { Minus } from "./generated/minus";
import { Pause } from "./generated/pause";
import { Paw } from "./generated/paw";
import { Person } from "./generated/person";
import { Play } from "./generated/play";
import { Plus } from "./generated/plus";
import { RadialGauge } from "./generated/radialGauge";
import { Refresh } from "./generated/refresh";
import { Screen } from "./generated/screen";
import { Search } from "./generated/search";
import { Security } from "./generated/security";
import { Smiley } from "./generated/smiley";
import { Sparkle } from "./generated/sparkle";
import { Warning } from "./generated/warning";
import { Wordmark } from "./generated/wordmark";
import { World } from "./generated/world";

export type IconComponent = FC<SVGProps<SVGSVGElement>>;

export const iconLibrary: Record<string, IconComponent> = {
  arrowUpRight: ArrowUpRight,
  atSymbol: AtSymbol,
  ball: Ball,
  calendar: Calendar,
  check: Check,
  checkbox: Checkbox,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronsLeftRight: ChevronsLeftRight,
  chevronUp: ChevronUp,
  clipboard: Clipboard,
  close: Close,
  computer: Computer,
  copy: Copy,
  danger: Danger,
  dark: Dark,
  document: Document,
  enter: Enter,
  eye: Eye,
  eyeDropper: EyeDropper,
  eyeOff: EyeOff,
  flag: Flag,
  food: Food,
  gift: Gift,
  help: Help,
  info: Info,
  light: Light,
  linearGauge: LinearGauge,
  link: Link,
  maximize: Maximize,
  minimize: Minimize,
  minus: Minus,
  pause: Pause,
  paw: Paw,
  person: Person,
  play: Play,
  plus: Plus,
  radialGauge: RadialGauge,
  refresh: Refresh,
  screen: Screen,
  search: Search,
  security: Security,
  smiley: Smiley,
  sparkle: Sparkle,
  warning: Warning,
  wordmark: Wordmark,
  world: World,
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;
