import { IconType } from "react-icons";

import {
  HiChevronUp,
  HiChevronDown,
  HiChevronRight,
  HiChevronLeft,
  HiOutlineArrowPath,
  HiOutlineSun,
  HiOutlineMoon,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiOutlineClipboard,
  HiOutlineMagnifyingGlass,
  HiOutlineLink,
  HiArrowUpRight,
  HiOutlineShieldCheck,
  HiOutlineSparkles,
  HiOutlineComputerDesktop,
  HiOutlineQuestionMarkCircle,
  HiOutlineInformationCircle,
  HiOutlineExclamationTriangle,
  HiOutlineExclamationCircle,
  HiOutlineCheckCircle,
  HiOutlineXMark,
  HiOutlineUser,
  HiOutlineEyeDropper,
  HiOutlineMinus,
  HiOutlinePlus,
  HiOutlineCalendar,
  HiOutlineDocumentDuplicate,
  HiOutlineCheck,
  HiOutlineArrowsPointingIn,
  HiOutlineArrowsPointingOut,
  HiOutlineFaceSmile,
  HiOutlineArrowTurnDownLeft,
  HiOutlinePlay,
  HiOutlinePause,
  HiOutlineBars3BottomLeft,
} from "react-icons/hi2";

import {
  IoAtOutline,
  IoFastFoodOutline,
  IoFlagOutline,
  IoFootballOutline,
  IoGiftOutline,
  IoGlobeOutline,
  IoPawOutline,
} from "react-icons/io5";
import { LuChevronsLeftRight, LuTextCursorInput } from "react-icons/lu";
import { PiBatteryFull, PiGauge } from "react-icons/pi";

export const iconLibrary: Record<string, IconType> = {
  chevronUp: HiChevronUp,
  chevronDown: HiChevronDown,
  chevronRight: HiChevronRight,
  chevronLeft: HiChevronLeft,
  chevronsLeftRight: LuChevronsLeftRight,
  refresh: HiOutlineArrowPath,
  light: HiOutlineSun,
  dark: HiOutlineMoon,
  help: HiOutlineQuestionMarkCircle,
  info: HiOutlineInformationCircle,
  warning: HiOutlineExclamationTriangle,
  danger: HiOutlineExclamationCircle,
  checkbox: HiOutlineCheck,
  check: HiOutlineCheckCircle,
  copy: HiOutlineDocumentDuplicate,
  eyeDropper: HiOutlineEyeDropper,
  clipboard: HiOutlineClipboard,
  person: HiOutlineUser,
  close: HiOutlineXMark,
  link: HiOutlineLink,
  arrowUpRight: HiArrowUpRight,
  minus: HiOutlineMinus,
  plus: HiOutlinePlus,
  calendar: HiOutlineCalendar,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  search: HiOutlineMagnifyingGlass,
  security: HiOutlineShieldCheck,
  sparkle: HiOutlineSparkles,
  computer: HiOutlineComputerDesktop,
  minimize: HiOutlineArrowsPointingIn,
  maximize: HiOutlineArrowsPointingOut,
  smiley: HiOutlineFaceSmile,
  paw: IoPawOutline,
  food: IoFastFoodOutline,
  ball: IoFootballOutline,
  world: IoGlobeOutline,
  gift: IoGiftOutline,
  symbol: IoAtOutline,
  flag: IoFlagOutline,
  wordmark: LuTextCursorInput,
  enter: HiOutlineArrowTurnDownLeft,
  play: HiOutlinePlay,
  pause: HiOutlinePause,
  screen: HiOutlineComputerDesktop,
  document: HiOutlineBars3BottomLeft,
  radialGauge: PiGauge,
  linearGauge: PiBatteryFull
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;
